on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/simple-upstream-monitor.yaml@feat/upstream-sync
    with:
      source-repo: "rerun-io/rerun"
