on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  monitor-upstream-release:
    uses: canonical/robotics-actions-workflows/.github/workflows/upstream-gh-tag-monitor.yaml@feat/upstream-sync
    with:
      source-repo: "rerun-io/rerun"
