name: promote

on:
  workflow_dispatch:

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/promote.yaml@main
    secrets:
      snapstore-login: ${{ secrets.SNAPSTORE_LOGIN }}
    with:
      snap: rerun
      from-channel: 'latest/candidate'
      to-channel: 'latest/stable'
