on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    with:
      snap-test-script: |
        rerun help
      snap-risk: candidate
    secrets:
      snapstore-login: ${{ secrets.SNAPSTORE_LOGIN }}
